name: Build and Test math

on:
  push:
    branches:
      - feature-math  # Adjust this to your branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Install Google Test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo mv lib/libgtest*.a /usr/lib/
      
      - name: Build project
        run: |
          g++ -std=c++17 -Wall -o test_math src/math.cpp src/main.cpp -lgtest -lgtest_main -pthread
      
      - name: Run tests
        run: |
          ./test_math